### PR TITLE
Use PEG to prevent bugs

### PR DESCRIPTION
**Pull request by Kuniwak**
- [x] Re-implement the parser with PEG
- [x] Implement a publisher
- [x] Implement a type builder for v1.2.0
- [x] Restore removed legacy tests for v1.2.0
- [x] Compatibility check for [tj/dox](https://github.com/tj/dox/blob/master/lib/dox.js#L387)

### CODE REVIEW

**Comment by zxqfox** [comment]
Tested just now:
- `package.json: main` file is absent (`lib/index` was moved to `lib/legacy/index`);
- not sure, but looks like there are different type objects (`node instanceof require('jsdoctypeparser/lib/legacy').Builder.TypeUnion`, etc...).

**Comment by Kuniwak** [comment]
Thanks, @zxqfox !

> not sure, but looks like there are different type objects 
Sorry, I forgot to simulate the TypeBuilder behavior...
I'm gonna implement the behavior.

And I think that a plain object AST is better, so the new parser return a plain object AST.
It makes more readable (instance type is not visible by JSON...).

**Comment by zxqfox** [comment]
@Kuniwak :100:%!

**Comment by Kuniwak** [comment]
What remained for compatibility check for tj/dox.

**Comment by Kuniwak** [comment]
I tried the following code based on [tj/dox example](https://github.com/tj/dox#usage-examples).
And looks good for me.

```javascript
/**
 * Escape the given `html`.
 *
 * @example
 *     utils.escape('<script></script>')
 *     // => '&lt;script&gt;&lt;/script&gt;'
 *
 * @param {string[][]} html string to be escaped
 * @return {{String}} escaped html
 * @api public
 */

exports.escape = function(html){
  return String(html)
    .replace(/&(?!\w+;)/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
};
```

**Comment by Kuniwak** [comment]
@zxqfox Ready to be v1.2.0.
Finally, would you re-test it please?

**Comment by zxqfox** [comment]
@Kuniwak trying... ;-)

**Comment by zxqfox** [comment]
@Kuniwak It works! Sorry for delay :palm_tree:

**Comment by zxqfox** [comment]
@Kuniwak Hm. I've found one trouble. What about multiline declarations?

```
/**
 * @returns {{rules: function(Object),
 *   configure: function(Object),
 *   cases: function(Array.<TestCase{it: string, code: Function, ?rules: Object, ?errors: *, ?skip: boolean}>),
 *   check: function(string)}}
 */
```

This one are parsed without syntax errors in current version:
```js
{rules: function(Object), configure: function(Object), cases: function(Array.<TestCase{it: string, code: Function, ?rules: Object, ?errors: *, ?skip: boolean}>), check: function(string)}
```

**Comment by zxqfox** [comment]
False error. All is fine. There is an error in syntax. :+1: NICE!!!

**Comment by Kuniwak** [comment]
Thanks, @zxqfox !

**Pull request merged**
